# Generated by Django 5.0.7 on 2024-08-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("guid", models.CharField(max_length=100, unique=True)),
                ("fin", models.CharField(blank=True, max_length=100, null=True)),
                ("sea", models.BooleanField(default=False)),
                ("tmg", models.BooleanField(default=False)),
                ("efis", models.BooleanField(default=False)),
                ("fnpt", models.IntegerField(default=0)),
                ("make", models.CharField(blank=True, max_length=100, null=True)),
                ("run2", models.BooleanField(default=False)),
                ("class_type", models.IntegerField(db_column="class", default=0)),
                ("model", models.CharField(max_length=100)),
                ("power", models.IntegerField(default=1)),
                ("seats", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("kg5700", models.BooleanField(default=False)),
                ("rating", models.CharField(blank=True, max_length=100, null=True)),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("complex", models.BooleanField(default=False)),
                ("cond_log", models.IntegerField(default=0)),
                ("fav_list", models.BooleanField(default=False)),
                ("category", models.IntegerField(default=0)),
                ("high_perf", models.BooleanField(default=False)),
                ("sub_model", models.CharField(blank=True, max_length=100, null=True)),
                ("aerobatic", models.BooleanField(default=False)),
                ("ref_search", models.CharField(blank=True, max_length=100, null=True)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("tailwheel", models.BooleanField(default=False)),
                ("default_app", models.IntegerField(default=0)),
                ("default_log", models.IntegerField(default=0)),
                ("default_ops", models.IntegerField(default=0)),
                ("device_code", models.IntegerField(default=0)),
                ("aircraft_code", models.CharField(max_length=100)),
                ("default_launch", models.IntegerField(default=0)),
                ("record_modified", models.DateTimeField()),
            ],
        ),
    ]
